from enum import Enum


class ExitCode(Enum):
    OK = 0
    MISSING_ARGUMENT = 10
    READ_ERROR = 11
    BAD_XML = 31
    UNEXPECTED_XML_STRUCTURE = 32
    SEMANTIC_ERROR = 52
    BAD_OPERAND_TYPE = 53
    UNDEFINED_VARIABLE = 54
    UNDEFINED_FRAME = 55
    MISSING_VALUE = 56
    BAD_OPERAND_VALUE = 57
    BAD_STRING_OPERATION = 58
    INTERNAL_ERROR = 99
